version: '3.6'
services:
  node-exporter:
    image: "prom/node-exporter"
    container_name: "node-exporter"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    ports:
      - 9100:9100
    networks:
      subnet1:
        ipv4_address: 172.24.0.2
    restart: always
    
  prometheus:
    image: prom/prometheus:latest
    user: root
    container_name: prometheus
    volumes:
      - /home/test/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention=200h
    restart: always
    ports:
      - 9090:9090
    networks:
      subnet1:
        ipv4_address: 172.24.0.3
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      subnet1:
        ipv4_address: 172.24.0.4
networks:
  subnet1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/24
